// Code generated by mockery v2.53.3. DO NOT EDIT.

package postgres

import (
	context "context"
	media_repository "pinstack-post-service/internal/domain/ports/output/media"

	mock "github.com/stretchr/testify/mock"

	post_repository "pinstack-post-service/internal/domain/ports/output/post"

	tag_repository "pinstack-post-service/internal/domain/ports/output/tag"
)

// Transaction is an autogenerated mock type for the Transaction type
type Transaction struct {
	mock.Mock
}

type Transaction_Expecter struct {
	mock *mock.Mock
}

func (_m *Transaction) EXPECT() *Transaction_Expecter {
	return &Transaction_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx
func (_m *Transaction) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transaction_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type Transaction_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Transaction_Expecter) Commit(ctx interface{}) *Transaction_Commit_Call {
	return &Transaction_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *Transaction_Commit_Call) Run(run func(ctx context.Context)) *Transaction_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Transaction_Commit_Call) Return(_a0 error) *Transaction_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_Commit_Call) RunAndReturn(run func(context.Context) error) *Transaction_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// MediaRepository provides a mock function with no fields
func (_m *Transaction) MediaRepository() media_repository.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MediaRepository")
	}

	var r0 media_repository.Repository
	if rf, ok := ret.Get(0).(func() media_repository.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(media_repository.Repository)
		}
	}

	return r0
}

// Transaction_MediaRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MediaRepository'
type Transaction_MediaRepository_Call struct {
	*mock.Call
}

// MediaRepository is a helper method to define mock.On call
func (_e *Transaction_Expecter) MediaRepository() *Transaction_MediaRepository_Call {
	return &Transaction_MediaRepository_Call{Call: _e.mock.On("MediaRepository")}
}

func (_c *Transaction_MediaRepository_Call) Run(run func()) *Transaction_MediaRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_MediaRepository_Call) Return(_a0 media_repository.Repository) *Transaction_MediaRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_MediaRepository_Call) RunAndReturn(run func() media_repository.Repository) *Transaction_MediaRepository_Call {
	_c.Call.Return(run)
	return _c
}

// PostRepository provides a mock function with no fields
func (_m *Transaction) PostRepository() post_repository.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PostRepository")
	}

	var r0 post_repository.Repository
	if rf, ok := ret.Get(0).(func() post_repository.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(post_repository.Repository)
		}
	}

	return r0
}

// Transaction_PostRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostRepository'
type Transaction_PostRepository_Call struct {
	*mock.Call
}

// PostRepository is a helper method to define mock.On call
func (_e *Transaction_Expecter) PostRepository() *Transaction_PostRepository_Call {
	return &Transaction_PostRepository_Call{Call: _e.mock.On("PostRepository")}
}

func (_c *Transaction_PostRepository_Call) Run(run func()) *Transaction_PostRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_PostRepository_Call) Return(_a0 post_repository.Repository) *Transaction_PostRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_PostRepository_Call) RunAndReturn(run func() post_repository.Repository) *Transaction_PostRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *Transaction) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transaction_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type Transaction_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Transaction_Expecter) Rollback(ctx interface{}) *Transaction_Rollback_Call {
	return &Transaction_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *Transaction_Rollback_Call) Run(run func(ctx context.Context)) *Transaction_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Transaction_Rollback_Call) Return(_a0 error) *Transaction_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_Rollback_Call) RunAndReturn(run func(context.Context) error) *Transaction_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// TagRepository provides a mock function with no fields
func (_m *Transaction) TagRepository() tag_repository.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TagRepository")
	}

	var r0 tag_repository.Repository
	if rf, ok := ret.Get(0).(func() tag_repository.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tag_repository.Repository)
		}
	}

	return r0
}

// Transaction_TagRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagRepository'
type Transaction_TagRepository_Call struct {
	*mock.Call
}

// TagRepository is a helper method to define mock.On call
func (_e *Transaction_Expecter) TagRepository() *Transaction_TagRepository_Call {
	return &Transaction_TagRepository_Call{Call: _e.mock.On("TagRepository")}
}

func (_c *Transaction_TagRepository_Call) Run(run func()) *Transaction_TagRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_TagRepository_Call) Return(_a0 tag_repository.Repository) *Transaction_TagRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_TagRepository_Call) RunAndReturn(run func() tag_repository.Repository) *Transaction_TagRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransaction creates a new instance of Transaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transaction {
	mock := &Transaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
